<a href="https://colab.research.google.com/github/Srijan9/Image-Classifier-Mini-Project/blob/main/mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install bing-image-downloader

In [2]:
import bing_image_downloader

In [3]:
!mkdir images

In [4]:
from bing_image_downloader import downloader
downloader.download('apple fruit', limit=30,  output_dir='images', adult_filter_off=True, force_replace=False, timeout=60)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://www.healthbenefitstimes.com/9/gallery/apple/Apple-fruit.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://www.chhajedgarden.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/0/4/04_apples.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://dairyfoodblog.files.wordpress.com/2017/08/apple4.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.znaturalfoods.com/1501-thickbox_default/apple-powder-organic.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.theayurveda.org/wp-content/uploads/2015/08/Apple-fruit.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://dreamicus.com/data/apple/apple-01.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://aggie-horticulture.tamu.edu/vegetable/files/2011/10/apple26.jpg
[%] File Downloaded !

[%] Downloading Image #8 from https://oneflowyogastudio.com/w

In [5]:
from bing_image_downloader import downloader
downloader.download('lemon', limit=30,  output_dir='images', adult_filter_off=True, force_replace=False, timeout=60)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://lemonconcentrate.com/wp-content/uploads/2017/08/limon-1-1.png
[%] File Downloaded !

[%] Downloading Image #2 from https://universityhealthnews.com/media/lemon-health-benefits-1.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://healthyfoodhouse.com/wp-content/uploads/2015/03/14-secret-powers-of-lemon.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://www.natural-cure.org/wp-content/uploads/wonders-of-lemon.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.thetutuguru.com.au/wp-content/uploads/2015/03/LISBON.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://sc02.alicdn.com/kf/UTB8HhMSGFfFXKJk43Otq6xIPFXap/946577091/UTB8HhMSGFfFXKJk43Otq6xIPFXap.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://guesthousediabatalo.com/website/wp-content/uploads/2019/10/lemon-room.png
[%] File Downloaded !

[%] Downloading Image #8 fro

In [6]:
import numpy as np
from skimage.transform import resize
from skimage.io import imread
import matplotlib.pyplot as plt
import os 

target=[]   #output
images=[]   #in matrix format
flat_data=[] #image in vector format


DATADIR= '/content/images'
CATEGORIES= ['apple fruit', 'lemon']


for category in CATEGORIES:
  class_num= CATEGORIES.index(category)
  path=os.path.join(DATADIR,category)
  for img in os.listdir(path):
    img_array= imread(os.path.join(path,img))
    img_resized=resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

target=np.array(target)  
images=np.array(images)   
flat_data=np.array(flat_data)

In [7]:
import pandas as pd
df=pd.DataFrame(flat_data)
df['Target']= target
df

0         1         2  ...     67498     67499  Target
0   0.992157  0.992157  0.992157  ...  0.992157  0.992157       0
1   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
2   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
3   0.845752  0.873856  0.977669  ...  0.853268  0.973856       0
4   0.223516  0.253725  0.073346  ...  0.136878  0.012928       0
5   0.945098  0.945098  0.945098  ...  0.964706  0.964706       0
6   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
7   0.992157  0.992157  0.992157  ...  0.992157  0.992157       0
8   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
9   0.383529  0.198130  0.144013  ...  0.101176  0.035294       0
10  1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
11  0.996078  0.996078  0.996078  ...  0.996078  0.996078       0
12  1.000000  1.000000  1.000000  ...  0.886275  0.925490       0
13  1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
14  0.992157  0.992157  0.992157  ...  0.992157  0.992157       0
15  0.996078  0.996078  0.996078  ...  0.996078  0.996078       0
16  0.992157  0.996078  0.994118  ...  0.098039  0.015686       0
17  0.992157  0.992157  0.992157  ...  0.992157  0.992157       0
18  0.698039  0.764706  0.909804  ...  0.933333  0.909412       0
19  0.925490  0.925490  0.925490  ...  0.901961  0.894118       0
20  0.996078  0.996078  0.996078  ...  0.996078  0.996078       0
21  0.996078  0.996078  0.996078  ...  0.992157  0.996078       0
22  1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
23  0.996078  0.996078  0.996078  ...  0.996078  0.996078       0
24  0.996078  0.996078  0.996078  ...  0.996078  0.996078       0
25  0.634033  0.598039  0.203922  ...  0.239216  0.190196       0
26  0.325490  0.313725  0.239216  ...  0.666667  0.631373       0
27  0.992157  0.992157  0.992157  ...  0.992157  0.992157       0
28  0.607843  0.164706  0.140980  ...  0.254314  0.123137       0
29  0.846208  0.662876  0.388235  ...  0.517647  0.191437       0
30  0.474510  0.462745  0.380392  ...  0.600067  0.580392       1
31  0.577801  0.569307  0.370667  ...  0.529412  0.764366       1
32  0.996078  0.994118  0.165359  ...  0.994118  0.165359       1
33  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
34  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
35  0.812418  0.781046  0.714379  ...  0.418954  0.328758       1
36  0.121569  0.250980  0.219608  ...  0.662238  0.151608       1
37  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
38  0.992157  0.992157  0.992157  ...  0.328535  0.239216       1
39  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
40  0.556863  0.701961  0.905882  ...  0.937255  0.980392       1
41  0.996078  0.994118  0.165359  ...  0.994118  0.165359       1
42  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
43  0.996078  0.994118  0.165359  ...  0.541529  0.420928       1
44  0.000000  0.000000  0.000000  ...  0.000000  0.000000       1
45  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
46  0.917647  0.917647  0.941176  ...  0.945098  0.945098       1
47  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
48  0.898572  0.720471  0.010693  ...  0.193595  0.019608       1
49  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
50  1.000000  1.000000  1.000000  ...  1.000000  1.000000       1
51  0.120209  0.206173  0.049961  ...  0.191817  0.117647       1
52  0.000000  0.000000  0.000000  ...  0.000000  0.000000       1
53  0.945098  0.895359  0.790719  ...  0.682353  0.667490       1
54  0.800000  0.784314  0.772549  ...  0.289229  0.243137       1
55  0.996078  0.994118  0.165359  ...  0.994118  0.165359       1
56  0.223529  0.160564  0.133553  ...  0.369948  0.079098       1
57  0.980392  0.984314  0.992157  ...  0.972549  0.972549       1
58  0.826797  0.728105  0.486275  ...  0.528214  0.402070       1
59  0.807843  0.827451  0.850980  ...  0.941176  0.

In [8]:
#splitting into test and train 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(flat_data,target,random_state=0)

In [9]:
#using SVM model 
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid=[
            {'C':[1,10,100,1000], 'kernel':['linear']},
            {'C':[1,10,100,1000], 'gamma':[0.001,0.0001],'kernel':['rbf']}  
            
]
svc=svm.SVC(probability=True)
clf=GridSearchCV(svc, param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [10]:
y_pred=clf.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1])

In [11]:
y_test

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [13]:
accuracy_score(y_pred,y_test)

0.8666666666666667

In [14]:
confusion_matrix(y_pred,y_test)

array([[6, 1],
       [1, 7]])

In [15]:
#saving the model 
import pickle 
pickle.dump(clf,open('img_model.p','wb'))

In [16]:
model=pickle.load(open('img_model.p','rb'))

In [ ]:
#testing
flat_data=[]
url=input('Enter your URL')
img=imread(url)
img_resized= resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data=np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out=model.predict(flat_data)
y_out=CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT:{y_out}')
